### ISSUE TITLE
Legend on ratio raw data curve

### ISSUE THREAD

**Issue by IsabellePickles** [lawrencecollins/Ca-Flex-Analysis#10]
Please could you change the control legend from EA+DMSO to 0 nM to align with the other conditions? And just have the compound name as the legend title. Or have an option to alter the legend? Or if I change it on the plate map would that work?

Hope that makes sense!

**Comment by lawrencecollins** [comment]
Great shout - yep I'll add some more customisability to this!

**Comment by lawrencecollins** [comment]
This should be all fixed, I might add some more settings, but for the time being the control will automatically be set to '0 Units' with just the compound name for the legend title

**Comment by IsabellePickles** [comment]
ok great thanks!
