### ISSUE TITLE
Add an option to change colours for the conditions?

### ISSUE THREAD

**Issue by IsabellePickles** [lawrencecollins/Ca-Flex-Analysis#11]
Please could you add an option to change the colour scheme of the curves in the raw traces. I like to have different colours for different cell types!

Thanks (and sorry if this already exists...)!

**Comment by lawrencecollins** [comment]
Are you referring to the visualise_assay function? If so you can change the colours by using the 'colorby' attribute. This can be set to any of the columns in your plate map file. You can also change the colour scheme to any of the built-in matplotlib colormaps using 'colormap = 'insert_name' within the function. (I might change this attribute to 'cmap' at some point to be more in line with the matplotlib jargon). Any of the functions which can be colour-coded have this attribute. Info on good colormaps to use can be found here: https://matplotlib.org/3.1.0/tutorials/colors/colormaps.html

Hope this helps!!!
